Allow fileName to be an Array of Function
mhkeller/indian-ocean pull request #60
Opened 2017-08-30 13:32 UTC by aubergene

Accept array or function for fileName. Work in progress

Do you think `src/utils/path.js` is the right approach?

Closes #58

2017-08-30 14:38 UTC, mhkeller commented
Cool. Looks like `discernPath` still needs to be exported for the CI to check the tests. We should also probably include a test for each function that this could apply to in order to ensure coverage. Perhaps there's a better way to structure tests to allow for more variation like this without writing a bunch of new things.

2017-08-30 14:48 UTC, aubergene commented
Ah yes. I didn't check in a build version. Yeah, I was unsure what is easiest with the tests, perhaps we could add a helper method into the tests which cycles over the different ways of constructing a path.

Adding an `.editorconfig` would be great

I got some whitespace diff issue for generating Yaml when running tests. I think it's because when I did npm install I got a different version (js-yaml 3.9.1). Perhaps add a lock file?

I also got an issue about `rollup-plugin-node-builtins` missing for build:browser, but I'm guessing it's still a work in progress

2017-08-30 14:48 UTC, aubergene commented
Do you think this functionality and approach looks good though in general?

2017-08-30 14:51 UTC, mhkeller commented
Ya I think so. I can't think of a simpler alternative.

2017-09-01 01:34 UTC, mhkeller commented
what was the `rollup-plugin-node-builtins ` problem? Maybe open that up as an issue.

2017-09-08 03:15 UTC, mhkeller requested changes

2017-09-08 03:15 UTC, mhkeller commented on src/utils/path.js
> +  var args = (arguments.length === 1 ? arguments[0] : Array.apply(null, arguments))
This doesn't join paths that are strings: https://codepen.io/anon/pen/gxNGjv

2017-09-08 05:46 UTC, mhkeller commented
@aubergene FYI the yaml and rollup plugin issues should be fixed. There's also now an .editorconfig and package-lock.json. I think the next step for this is:

1. Fix the `joinPath` above
2. Add tests for all existing functions that take a filePath

2017-09-19 10:52 UTC, aubergene commented
I think this is good now. The tests currently use a mix of strings and arrays but do the joining themselves, so we could just remove `path.join`.

2017-09-20 02:50 UTC, mhkeller commented
Looks good overall. If you do the below, I'll update the docs if that sounds like a deal. It'd be nice to include this in 2.1.0. 

What do you mean by we could remove `path.join`? Do you mean test other functions by changing how they load in data. It would be cleaner to add two tests to each function so there isn't overlap.

I think something like `getPath` could be a better name. The `discern` functions are all about choosing a function based on evidence in the path. This function does something to a path.

1. Needs to be added to `readData`, `readDataSync` and `readdir`. The latter is used by both `readdirFilter` and `readdirFilterSync` so no need to add them there.
2. Needs tests using the functions affected. For example, something like this for `readDataSync` if you inserted this at the top on line 27:

```js
var testDataArr = function (morePath) {
  return [__dirname, 'data'].concat(morePath)
}
```

and then these tests at line 580

```js
    describe('json', function () {
      it('should match expected json with array path', function () {
        var json = io.readDataSync(testDataArr(['json', 'basic.json']))
        assertBasicValid(json)
      })
    })

    describe('json', function () {
      it('should match expected json with function path', function () {
        var json = io.readDataSync(function () {
          return testDataPath('json/basic.json')
        })
        assertBasicValid(json)
      })
    })
```

2017-10-03 14:46 UTC, aubergene commented
Yeah, the renaming is good. I started on it, and then started thinking more about problems when allowing a function. We have code paths where it would get called more than once. For instance in `appendData` which appears to read the data, append the new data and then write it out again. It would be tricky to structure this so that it would only call `getPath` once and also so that `readData` and `writeData` would do same too. I think either we drop the idea of it being a function and just join it. Hmm starting to question whether this is a good idea at all now

2017-10-11 06:09 UTC, mhkeller commented
Any updated thoughts on whether we should pursue this? Why would it have to be called more than once? After it gets called the first time it becomes a string and then `getPath` would simply return it and not join it again, no?

2017-10-26 15:21 UTC, closed without merging